---
title: "VHP4Safety short intro FAIR data"
subtitle: "conquer the chaos"
author: "Alyanne de Haan, PhD,  Marc Teunis, PhD"
site: bookdown::bookdown_site
output: Gmisc::docx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Workshop overview

## Why you want to complete this workshop

In this workshop we will focus on the I and R part of FAIR. 

Research projects are chaotic and we all know how hard it can be to keep track of manuscipt versions, changes to datasets, which figure was generated from which file, etc.. However, when building a data platform such as within VHP4Safety, it is very important that every datapoint can be retraced to its origin.

At the same time, many people store data in a way that works for them, but is almost impossible to reproduce once someone changes jobs. There are some easy systems to implement that conquer this chaos, make your work more productive, collaborations easier, and VHP4Safety possible. And also, save you a lot of time in the long run.


[TLDR] 

## Learning objectives

After this workshop you:

 - Can store your research projects (data, code, manuscripts, etc) in a future proof way, that fascilitates collaboration, and saves you a lot of time if you ever want to revisit, share or alter your projects. 
 - Have an idea of which information needs to be stored with data, and how to keep this together when collaborating with others.
 - Can start tomorrow (or well, next monday) with applying this in your everyday work.

## This reader
We build this reader both as a guide to the workshop, and for future reference. We will use some the exercises in the workshop, most of the text is there to make sure you can still use this material in a couple of months.

## Contents 

This workshop is devided in 2 parts: 

- Practical Data Handling (folder structure, metadata)
- Data sharing (communicating data, machine readable data)

## Schedule 

Total of 2 hours (12:00 - 14:00) 

Approximate durations for each item are displayed, because some exercises could last days or 5 minutes, depending on how deep you dive into them.

#### 12:00-12:30
 - 10-20 min welcome, everyone introduces themselves
 - 10 min broad introduction to research data management and FAIR data in VHP4Safety
 
#### 12:30-13:00 hands-on storing your current data 
 - 5 min intro Guerilla Analytics folder structure 
 - 15 min DIY analysing and cleaning your own current data storage ways (exercise A1)
 - 5 min intro metadata

#### 13:00-13:10 break

#### 13:10-13:50 hands-on sharing your current data
 - 10 min intro: The usual problematic workflow and how to do it FAIR
 - 5 min collaboration and digital data (exercise B1)
 - 15 min collaboration and digital data (exercise B2)
 - 10 min demo machine readable data and workflows
     
#### 13:50-14:00 closure

## Additional exercises and material

We added some useful (according to us) material and extra exercises to this reader, to give you a headstart when you want to continue improving your FAIR data skills.  

Some of the material has been reused from other courses, so keep that in mind. But we did not want to withold the possibility for you.

## TLDR

I you have absolutely no time other than reading this message, please try to do the following:

 - use a project centered folder structure, not a task centered one. 
 - always let name_of_your_document.docx be the current version. 
 - keep meta data with your data.
 - don't change data files, use versioning.
 - keep your data files in [tidy format](https://r4ds.had.co.nz/tidy-data.html).
 - don't use formatting to convey information in Excel (e.g. colors).
